name = "GeometricUnits"
uuid = "43c95830-f66f-43f3-8298-be5f3865d5b9"
authors = ["Abhimanyu Susobhanan <abhisrkckl@gmail.com>"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
